From CoqCP Require Import Options Imperative.
From stdpp Require Import numbers list strings.
Require Import Coq.Strings.Ascii.
Open Scope type_scope.
Inductive arrayIndex0 :=
| arraydef_0__current
| arraydef_0__count
| arraydef_0__scratchpad.

Definition environment0 : Environment arrayIndex0 := {| arrayType := fun name => match name with | arraydef_0__current => Z | arraydef_0__count => Z | arraydef_0__scratchpad => Z end; arrays := fun name => match name with | arraydef_0__current => repeat (0%Z) 1 | arraydef_0__count => repeat (0%Z) 1 | arraydef_0__scratchpad => repeat (0%Z) 1024 end |}.

#[export] Instance arrayIndexEqualityDecidable0 : EqDecision arrayIndex0 := ltac:(solve_decision).
#[export] Instance arrayTypeEqualityDecidable0 name : EqDecision (arrayType _ environment0 name).
Proof. simpl. repeat destruct name. all: solve_decision. Defined.
Inductive varsfuncdef_0__main :=
| vardef_0__main_what
| vardef_0__main_absolute.
#[export] Instance variableIndexEqualityDecidablevarsfuncdef_0__main : EqDecision varsfuncdef_0__main := ltac:(solve_decision).
Definition funcdef_0__main (bools : varsfuncdef_0__main -> bool) (numbers : varsfuncdef_0__main -> Z) (addresses : varsfuncdef_0__main -> list Z): Action (WithArrays _ (arrayType _ environment0)) withArraysReturnValue unit := eliminateLocalVariables bools numbers addresses (((addInt 32 (addInt 32 (addInt 32 (shiftLeft 32 (((Done _ _ _ 0%Z) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((Done _ _ _ 24%Z) >>= fun x => Done _ _ _ (coerceInt x 32))) (shiftLeft 32 (((Done _ _ _ 1%Z) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((Done _ _ _ 16%Z) >>= fun x => Done _ _ _ (coerceInt x 32)))) (shiftLeft 32 (((Done _ _ _ 2%Z) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((Done _ _ _ 8%Z) >>= fun x => Done _ _ _ (coerceInt x 32)))) (((Done _ _ _ 3%Z) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main x) >>= fun x => Done _ _ _ (coerceInt x 32))) >>= fun x => numberLocalSet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (vardef_0__main_what) x) >>=
fun _ => ((((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__count) x) >>= fun x => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 32)) >>= fun y => Done _ _ _ (bool_decide (x = y))) >>= fun x => if x then (
  ((Done _ _ _ 0%Z) >>= fun x => ((numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (vardef_0__main_what)) >>= fun tuple_element_0 => Done _ _ _ (tuple_element_0)) >>= fun y => store arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__current) x y) >>=
  fun _ => Done _ _ _ tt
) else (
  Done _ _ _ tt
)) >>=
fun _ => (((numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (vardef_0__main_what)) >>= fun x => ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__current) x) >>= fun y => Done _ _ _ (bool_decide (x = y))) >>= fun x => if x then (
  ((Done _ _ _ 0%Z) >>= fun x => ((addInt 32 ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__count) x) ((Done _ _ _ 1%Z) >>= fun x => Done _ _ _ (coerceInt x 32))) >>= fun tuple_element_0 => Done _ _ _ (tuple_element_0)) >>= fun y => store arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__count) x y) >>=
  fun _ => Done _ _ _ tt
) else (
  ((Done _ _ _ 0%Z) >>= fun x => ((subInt 32 ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__count) x) ((Done _ _ _ 1%Z) >>= fun x => Done _ _ _ (coerceInt x 32))) >>= fun tuple_element_0 => Done _ _ _ (tuple_element_0)) >>= fun y => store arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__count) x y) >>=
  fun _ => Done _ _ _ tt
)) >>=
fun _ => ((Done _ _ _ 0%Z) >>= fun x => ((shiftRight 32 ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__count) x) ((Done _ _ _ 24%Z) >>= fun x => Done _ _ _ (coerceInt x 32))) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main x y) >>=
fun _ => ((Done _ _ _ 1%Z) >>= fun x => ((andBits (shiftRight 32 ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__count) x) ((Done _ _ _ 16%Z) >>= fun x => Done _ _ _ (coerceInt x 32))) ((Done _ _ _ 255%Z) >>= fun x => Done _ _ _ (coerceInt x 32))) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main x y) >>=
fun _ => ((Done _ _ _ 2%Z) >>= fun x => ((andBits (shiftRight 32 ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__count) x) ((Done _ _ _ 8%Z) >>= fun x => Done _ _ _ (coerceInt x 32))) ((Done _ _ _ 255%Z) >>= fun x => Done _ _ _ (coerceInt x 32))) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main x y) >>=
fun _ => (divIntUnsigned (Done _ _ _ 3%Z) (Done _ _ _ 5%Z)) >>=
fun _ => (divInt64Signed (Done _ _ _ 3%Z) (Done _ _ _ 5%Z)) >>=
fun _ => ((Done _ _ _ 3%Z) >>= fun x => ((andBits ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__count) x) ((Done _ _ _ 255%Z) >>= fun x => Done _ _ _ (coerceInt x 32))) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main x y) >>=
fun _ => ((addressLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (vardef_0__main_absolute)) >>= fun address => ((Done _ _ _ 2000%Z) >>= fun x => Done _ _ _ (coerceInt x 256)) >>= fun money => donate _ _ _ money address) >>=
fun _ => ((addressLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (vardef_0__main_absolute)) >>= fun address => ((Done _ _ _ 2000%Z) >>= fun x => Done _ _ _ (coerceInt x 256)) >>= fun money => ((Done _ _ _ 1024%Z) >>= fun x => Done _ _ _ (coerceInt x 64)) >>= fun size => @invokeWithArrays _ (arrayType _ environment0) _ money address arraydef_0__scratchpad size ltac:(reflexivity)) >>=
fun _ => ((getSender _ _ _) >>= fun address => (getMoney _ _ _) >>= fun money => ((Done _ _ _ 1024%Z) >>= fun x => Done _ _ _ (coerceInt x 64)) >>= fun size => @invokeWithArrays _ (arrayType _ environment0) _ money address arraydef_0__scratchpad size ltac:(reflexivity)) >>=
fun _ => ((((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte0 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte1 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte2 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte3 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte4 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte5 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte6 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte7 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte8 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte9 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte10 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte11 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte12 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte13 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte14 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte15 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte16 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte17 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte18 => ((Done _ _ _ 0%Z) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun byte19 => Done _ _ _ [byte0;byte1;byte2;byte3;byte4;byte5;byte6;byte7;byte8;byte9;byte10;byte11;byte12;byte13;byte14;byte15;byte16;byte17;byte18;byte19]) >>= fun address => (getMoney _ _ _) >>= fun money => ((Done _ _ _ 1024%Z) >>= fun x => Done _ _ _ (coerceInt x 64)) >>= fun size => @invokeWithArrays _ (arrayType _ environment0) _ money address arraydef_0__scratchpad size ltac:(reflexivity)) >>=
fun _ => Done _ _ _ tt).
