From CoqCP Require Import Options Imperative.
From stdpp Require Import numbers list strings.
Require Import Coq.Strings.Ascii.
Open Scope type_scope.
Inductive arrayIndex0 :=
| arraydef_0__dp
| arraydef_0__message
| arraydef_0__n.

Definition environment0 : Environment arrayIndex0 := {| arrayType := fun name => match name with | arraydef_0__dp => Z | arraydef_0__message => Z | arraydef_0__n => Z end; arrays := fun name => match name with | arraydef_0__dp => repeat (0%Z) 1000000 | arraydef_0__message => repeat (0%Z) 1 | arraydef_0__n => repeat (0%Z) 1 end |}.

#[export] Instance arrayIndexEqualityDecidable0 : EqDecision arrayIndex0 := ltac:(solve_decision).
#[export] Instance arrayTypeEqualityDecidable0 name : EqDecision (arrayType _ environment0 name).
Proof. simpl. repeat destruct name. all: solve_decision. Defined.
Inductive varsfuncdef_0__getweight :=
| vardef_0__getweight_index.
#[export] Instance variableIndexEqualityDecidablevarsfuncdef_0__getweight : EqDecision varsfuncdef_0__getweight := ltac:(solve_decision).
Definition funcdef_0__getweight (bools : varsfuncdef_0__getweight -> bool) (numbers : varsfuncdef_0__getweight -> Z) (addresses : varsfuncdef_0__getweight -> list Z): Action (WithArrays _ (arrayType _ environment0)) withArraysReturnValue unit := eliminateLocalVariables bools numbers addresses (((Done _ _ _ 0%Z) >>= fun x => ((addInt 32 (addInt 32 (addInt 32 (multInt 32 (((multInt 64 (Done _ _ _ 4%Z) (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getweight (vardef_0__getweight_index))) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getweight x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((shiftLeft 64 (Done _ _ _ 1%Z) (Done _ _ _ 24%Z)) >>= fun x => Done _ _ _ (coerceInt x 32))) (multInt 32 (((addInt 64 (multInt 64 (Done _ _ _ 4%Z) (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getweight (vardef_0__getweight_index))) (Done _ _ _ 1%Z)) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getweight x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((shiftLeft 64 (Done _ _ _ 1%Z) (Done _ _ _ 16%Z)) >>= fun x => Done _ _ _ (coerceInt x 32)))) (multInt 32 (((addInt 64 (multInt 64 (Done _ _ _ 4%Z) (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getweight (vardef_0__getweight_index))) (Done _ _ _ 2%Z)) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getweight x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((shiftLeft 64 (Done _ _ _ 1%Z) (Done _ _ _ 8%Z)) >>= fun x => Done _ _ _ (coerceInt x 32)))) (((addInt 64 (multInt 64 (Done _ _ _ 4%Z) (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getweight (vardef_0__getweight_index))) (Done _ _ _ 3%Z)) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getweight x) >>= fun x => Done _ _ _ (coerceInt x 32))) >>= fun tuple_element_0 => Done _ _ _ (tuple_element_0)) >>= fun y => store arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getweight (arraydef_0__message) x y) >>=
fun _ => Done _ _ _ tt).
Inductive varsfuncdef_0__getvalue :=
| vardef_0__getvalue_index.
#[export] Instance variableIndexEqualityDecidablevarsfuncdef_0__getvalue : EqDecision varsfuncdef_0__getvalue := ltac:(solve_decision).
Definition funcdef_0__getvalue (bools : varsfuncdef_0__getvalue -> bool) (numbers : varsfuncdef_0__getvalue -> Z) (addresses : varsfuncdef_0__getvalue -> list Z): Action (WithArrays _ (arrayType _ environment0)) withArraysReturnValue unit := eliminateLocalVariables bools numbers addresses (((Done _ _ _ 0%Z) >>= fun x => ((addInt 32 (addInt 32 (addInt 32 (multInt 32 (((addInt 64 (multInt 64 (Done _ _ _ 4%Z) ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue (arraydef_0__n) x)) (multInt 64 (Done _ _ _ 4%Z) (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue (vardef_0__getvalue_index)))) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((shiftLeft 64 (Done _ _ _ 1%Z) (Done _ _ _ 24%Z)) >>= fun x => Done _ _ _ (coerceInt x 32))) (multInt 32 (((addInt 64 (addInt 64 (multInt 64 (Done _ _ _ 4%Z) ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue (arraydef_0__n) x)) (multInt 64 (Done _ _ _ 4%Z) (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue (vardef_0__getvalue_index)))) (Done _ _ _ 1%Z)) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((shiftLeft 64 (Done _ _ _ 1%Z) (Done _ _ _ 16%Z)) >>= fun x => Done _ _ _ (coerceInt x 32)))) (multInt 32 (((addInt 64 (addInt 64 (multInt 64 (Done _ _ _ 4%Z) ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue (arraydef_0__n) x)) (multInt 64 (Done _ _ _ 4%Z) (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue (vardef_0__getvalue_index)))) (Done _ _ _ 2%Z)) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((shiftLeft 64 (Done _ _ _ 1%Z) (Done _ _ _ 8%Z)) >>= fun x => Done _ _ _ (coerceInt x 32)))) (((addInt 64 (addInt 64 (multInt 64 (Done _ _ _ 4%Z) ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue (arraydef_0__n) x)) (multInt 64 (Done _ _ _ 4%Z) (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue (vardef_0__getvalue_index)))) (Done _ _ _ 3%Z)) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue x) >>= fun x => Done _ _ _ (coerceInt x 32))) >>= fun tuple_element_0 => Done _ _ _ (tuple_element_0)) >>= fun y => store arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getvalue (arraydef_0__message) x y) >>=
fun _ => Done _ _ _ tt).
Inductive varsfuncdef_0__storeresult :=
| vardef_0__storeresult_x.
#[export] Instance variableIndexEqualityDecidablevarsfuncdef_0__storeresult : EqDecision varsfuncdef_0__storeresult := ltac:(solve_decision).
Definition funcdef_0__storeresult (bools : varsfuncdef_0__storeresult -> bool) (numbers : varsfuncdef_0__storeresult -> Z) (addresses : varsfuncdef_0__storeresult -> list Z): Action (WithArrays _ (arrayType _ environment0)) withArraysReturnValue unit := eliminateLocalVariables bools numbers addresses (((Done _ _ _ 0%Z) >>= fun x => ((shiftRight 64 (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult (vardef_0__storeresult_x)) (Done _ _ _ 56%Z)) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult x y) >>=
fun _ => ((Done _ _ _ 1%Z) >>= fun x => ((andBits (shiftRight 64 (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult (vardef_0__storeresult_x)) (Done _ _ _ 48%Z)) (Done _ _ _ 255%Z)) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult x y) >>=
fun _ => ((Done _ _ _ 2%Z) >>= fun x => ((andBits (shiftRight 64 (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult (vardef_0__storeresult_x)) (Done _ _ _ 40%Z)) (Done _ _ _ 255%Z)) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult x y) >>=
fun _ => ((Done _ _ _ 3%Z) >>= fun x => ((andBits (shiftRight 64 (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult (vardef_0__storeresult_x)) (Done _ _ _ 32%Z)) (Done _ _ _ 255%Z)) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult x y) >>=
fun _ => ((Done _ _ _ 4%Z) >>= fun x => ((andBits (shiftRight 64 (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult (vardef_0__storeresult_x)) (Done _ _ _ 24%Z)) (Done _ _ _ 255%Z)) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult x y) >>=
fun _ => ((Done _ _ _ 5%Z) >>= fun x => ((andBits (shiftRight 64 (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult (vardef_0__storeresult_x)) (Done _ _ _ 16%Z)) (Done _ _ _ 255%Z)) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult x y) >>=
fun _ => ((Done _ _ _ 6%Z) >>= fun x => ((andBits (shiftRight 64 (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult (vardef_0__storeresult_x)) (Done _ _ _ 8%Z)) (Done _ _ _ 255%Z)) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult x y) >>=
fun _ => ((Done _ _ _ 7%Z) >>= fun x => ((andBits (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult (vardef_0__storeresult_x)) (Done _ _ _ 255%Z)) >>= fun x => Done _ _ _ (coerceInt x 8)) >>= fun y => setByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__storeresult x y) >>=
fun _ => Done _ _ _ tt).
Inductive varsfuncdef_0__getlimit : Type :=.
#[export] Instance variableIndexEqualityDecidablevarsfuncdef_0__getlimit : EqDecision varsfuncdef_0__getlimit := ltac:(solve_decision).
Definition funcdef_0__getlimit (bools : varsfuncdef_0__getlimit -> bool) (numbers : varsfuncdef_0__getlimit -> Z) (addresses : varsfuncdef_0__getlimit -> list Z): Action (WithArrays _ (arrayType _ environment0)) withArraysReturnValue unit := eliminateLocalVariables bools numbers addresses (((Done _ _ _ 0%Z) >>= fun x => ((addInt 32 (addInt 32 (addInt 32 (multInt 32 (((multInt 64 (Done _ _ _ 8%Z) ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getlimit (arraydef_0__n) x)) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getlimit x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((shiftLeft 64 (Done _ _ _ 1%Z) (Done _ _ _ 24%Z)) >>= fun x => Done _ _ _ (coerceInt x 32))) (multInt 32 (((multInt 64 (Done _ _ _ 8%Z) ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getlimit (arraydef_0__n) x)) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getlimit x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((shiftLeft 64 (Done _ _ _ 1%Z) (Done _ _ _ 16%Z)) >>= fun x => Done _ _ _ (coerceInt x 32)))) (multInt 32 (((multInt 64 (Done _ _ _ 8%Z) ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getlimit (arraydef_0__n) x)) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getlimit x) >>= fun x => Done _ _ _ (coerceInt x 32)) ((shiftLeft 64 (Done _ _ _ 1%Z) (Done _ _ _ 8%Z)) >>= fun x => Done _ _ _ (coerceInt x 32)))) (((multInt 64 (Done _ _ _ 8%Z) ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getlimit (arraydef_0__n) x)) >>= fun x => readByte arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getlimit x) >>= fun x => Done _ _ _ (coerceInt x 32))) >>= fun tuple_element_0 => Done _ _ _ (tuple_element_0)) >>= fun y => store arrayIndex0 (arrayType _ environment0) varsfuncdef_0__getlimit (arraydef_0__message) x y) >>=
fun _ => Done _ _ _ tt).
Inductive varsfuncdef_0__main :=
| vardef_0__main_limit.
#[export] Instance variableIndexEqualityDecidablevarsfuncdef_0__main : EqDecision varsfuncdef_0__main := ltac:(solve_decision).
Definition funcdef_0__main (bools : varsfuncdef_0__main -> bool) (numbers : varsfuncdef_0__main -> Z) (addresses : varsfuncdef_0__main -> list Z): Action (WithArrays _ (arrayType _ environment0)) withArraysReturnValue unit := eliminateLocalVariables bools numbers addresses (((Done _ _ _ 0%Z) >>= fun x => ((divIntUnsigned (subInt 64 (getCommunicationSize _ _ _) (Done _ _ _ 4%Z)) (Done _ _ _ 8%Z)) >>= fun tuple_element_0 => Done _ _ _ (tuple_element_0)) >>= fun y => store arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__n) x y) >>=
fun _ => ((Done _ _ _ (fun x => 0%Z)) >>= fun x => (Done _ _ _ (fun x => false)) >>= fun y => (Done _ _ _ (fun x => repeat 0%Z 20)) >>= fun z => liftToWithLocalVariables (funcdef_0__getlimit y x z)) >>=
fun _ => ((((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__message) x) >>= fun x => Done _ _ _ (coerceInt x 64)) >>= fun x => numberLocalSet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (vardef_0__main_limit) x) >>=
fun _ => ((addInt 64 ((Done _ _ _ 0%Z) >>= fun x => retrieve arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (arraydef_0__n) x) (Done _ _ _ 1%Z)) >>= fun x => loop (Z.to_nat x) (fun binder_0_intermediate => let binder_0 := Done (WithLocalVariables arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main) withLocalVariablesReturnValue _ (Z.sub (Z.sub x (Z.of_nat binder_0_intermediate)) 1%Z) in dropWithinLoop ((
  (liftToWithinLoop ((addInt 64 (numberLocalGet arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main (vardef_0__main_limit)) (Done _ _ _ 1%Z)) >>= fun x => loop (Z.to_nat x) (fun binder_1_intermediate => let binder_1 := Done (WithLocalVariables arrayIndex0 (arrayType _ environment0) varsfuncdef_0__main) withLocalVariablesReturnValue _ (Z.sub (Z.sub x (Z.of_nat binder_1_intermediate)) 1%Z) in dropWithinLoop ((
    Done _ _ _ tt
  ))))) >>=
  fun _ => Done _ _ _ tt
)))) >>=
fun _ => Done _ _ _ tt).
