name: Build and Process JSON

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript with SWC
        run: npx swc compiler/ --out-dir compiler/dist --source-maps --config-file ./swc.config.json

      - name: Find and process *.module.json files
        run: |
          find . -name '*.module.json' | while read path; do
            node compiler/dist/cli ?json "$path"
          done
